apply plugin: 'java-library'
apply plugin: 'maven-publish'

publishing {
	publications {
		maven(MavenPublication) {
			groupId = 'com.example'
			artifactId = 'kafka'
			version = "${kafkaVersion}"

			from components.java
		}
	}

	repositories {
		maven {
			url "${nexusUrl}"
			credentials {
				username "${nexusUsername}"
				password "${nexusPassword}"
			}
		}
	}
}

dependencies {
	compileOnly "org.springframework.boot:spring-boot-starter-web:${springBootExternalVersion}"

	implementation "org.springframework.kafka:spring-kafka:${kafkaExternalVersion}"
}
