rootProject.name = 'user-service'

include('api')
include('service')

gradle.allprojects {
    ext {
        // Nexus
        nexusGroup = NEXUS_GROUP
        nexusUrl = NEXUS_URL
        nexusUsername = NEXUS_USERNAME
        nexusPassword = NEXUS_PASSWORD

        apiVersion = '1.0.0'
        serviceVersion = '1.0.0'
    }
}

dependencyResolutionManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            url NEXUS_GROUP
            credentials {
                username NEXUS_USERNAME
                password NEXUS_PASSWORD
            }
        }
    }

    versionCatalogs {
        libsOuter {
            from('com.example:bom-outer:1.0.+')
        }

        libsInner {
            from('com.example:bom-inner:1.0.+')
        }
    }
}
